module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  corePlugins: { preflight: true },
  theme: {
    extend: {
      colors: {
        "addblue-bubblle": "var(--addblue-bubblle)",
        "adddark-blue": "var(--adddark-blue)",
        "addlight-green": "var(--addlight-green)",
        "addlight-grey": "var(--addlight-grey)",
        "addlight-purplle": "var(--addlight-purplle)",
        "addmid-grey": "var(--addmid-grey)",
        addsand: "var(--addsand)",
        "error-800": "var(--error-800)",
        "grey-scale100": "var(--grey-scale100)",
        "grey-scale25": "var(--grey-scale25)",
        "grey-scale300": "var(--grey-scale300)",
        "grey-scale400": "var(--grey-scale400)",
        "grey-scale500": "var(--grey-scale500)",
        "grey-scale600": "var(--grey-scale600)",
        "grey-scale700": "var(--grey-scale700)",
        "grey-scale900": "var(--grey-scale900)",
        "grey-scalewhite": "var(--grey-scalewhite)",
        "maindark-grey": "var(--maindark-grey)",
        maingrey: "var(--maingrey)",
        "mainlight-blue": "var(--mainlight-blue)",
        mainmilk: "var(--mainmilk)",
        mainwhite: "var(--mainwhite)",
        "primary500-main": "var(--primary500-main)",
        scoreai: "var(--scoreai)",
        scorecomm: "var(--scorecomm)",
        scoresol: "var(--scoresol)",
        "secondary-600": "var(--secondary-600)",
        "secondary500-main": "var(--secondary500-main)",
        "v-3blue-2": "var(--v-3blue-2)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      boxShadow: { "10-15": "var(--10-15)" },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
