// @ts-check
import { defineConfig, fontProviders } from 'astro/config';
import { createReadStream, statSync } from 'node:fs';
import { extname, join, normalize } from 'node:path';

// The logo, the favicon and the social cards belong to the site around this
// blog, not to this project, so in a production build they are simply
// site-relative URLs. In `astro dev` nothing serves them, so a writer
// previewing a post sees a broken logo. This hands those two paths to the
// published folder instead. Dev only: it changes nothing about the build.
const TYPES = {
  '.svg': 'image/svg+xml', '.png': 'image/png', '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg', '.webp': 'image/webp', '.mp4': 'video/mp4',
  '.ico': 'image/x-icon', '.css': 'text/css', '.js': 'text/javascript',
};

const serveSiteAssets = {
  name: 'fluencyfox-dev-assets',
  hooks: {
    'astro:server:setup': ({ server }) => {
      server.middlewares.use((req, res, next) => {
        const path = normalize(decodeURIComponent((req.url || '').split('?')[0]));
        if (!path.startsWith('/assets/') && !path.startsWith('/og/')) return next();
        const file = join(process.cwd(), '..', 'fluencyfox-site_6', path);
        try {
          if (!statSync(file).isFile()) return next();
        } catch {
          return next();
        }
        res.setHeader('Content-Type', TYPES[extname(file)] ?? 'application/octet-stream');
        createReadStream(file).pipe(res);
      });
    },
  },
};

// The blog is one part of a site that is otherwise hand-generated by
// build/build.mjs. Two things here keep the two halves consistent:
//
//   format: 'file'     writes <slug>.html, not <slug>/index.html, because
//                      Cloudflare Pages serves a file at /path and a folder
//                      at /path/ with a 307 from the slashless form. Every
//                      canonical on this site is slashless, so files it is.
//   trailingSlash      makes the links Astro writes match those canonicals.
//
// `emit.mjs` runs after the build and moves dist/ into the published folder.
export default defineConfig({
  site: 'https://fluencyfox.ai',
  base: '/blog',
  trailingSlash: 'never',
  outDir: './dist',
  build: { format: 'file', assets: '_astro' },
  compressHTML: true,

  // Self-hosted, preloaded, and served from our own origin. The rest of the
  // site still pulls these three families from Google, which costs a DNS
  // lookup, a TLS handshake and a round trip before any text can paint. Astro
  // also generates a metric-matched fallback for each one, so the page does
  // not jump when the real font arrives.
  fonts: [
    {
      provider: fontProviders.google(),
      name: 'Libre Franklin',
      cssVariable: '--font-ui',
      weights: [400, 500, 600, 700, 800],
      subsets: ['latin'],
      styles: ['normal'],
      fallbacks: ['Helvetica Neue', 'Arial', 'sans-serif'],
    },
    {
      provider: fontProviders.google(),
      name: 'Source Serif 4',
      cssVariable: '--font-serif',
      weights: ['400 600'],
      subsets: ['latin'],
      styles: ['normal'],
      fallbacks: ['Georgia', 'serif'],
    },
    {
      provider: fontProviders.google(),
      name: 'IBM Plex Mono',
      cssVariable: '--font-mono',
      weights: [400, 500, 600],
      subsets: ['latin'],
      styles: ['normal'],
      fallbacks: ['ui-monospace', 'monospace'],
    },
  ],

  // Images in a post get a srcset and intrinsic dimensions without anyone
  // remembering to write them, which is most of what Core Web Vitals asks
  // of a blog.
  image: { layout: 'constrained', responsiveStyles: true },
  integrations: [serveSiteAssets],
  markdown: {
    shikiConfig: {
      themes: { light: 'github-light', dark: 'github-dark' },
      wrap: true,
    },
  },
  // The chrome CSS and the site config live one level up, outside this
  // project's root, so Vite has to be told it may read them.
  vite: { server: { fs: { allow: ['..'] } } },
});
